Repository gachimind/backend, pull requests merged in 2023-02, with the labels that each got.

#154 FEAT : 유저 오늘 토탈 스코어 / 오늘 랭킹 / 게임 전체 스코어 API 구현
  project/dist/src/users/users.controller.js.map
  project/dist/src/users/users.service.d.ts
  project/dist/src/users/users.service.js
  project/dist/src/users/users.service.js.map
  project/dist/tsconfig.build.tsbuildinfo
  project/src/users/users.controller.ts
  project/src/users/users.service.ts
Labels: enhancement, :smile_cat: backend

#155 FIX : 이중 로그인시, 기존에 로그인했던 소켓 disconnect 처리 #115
  project/dist/src/games/dto/socketId-map.request.dto.d.ts
  project/dist/src/games/dto/socketId-map.request.dto.js
  project/dist/src/games/dto/socketId-map.request.dto.js.map
  project/dist/src/games/entities/socketIdMap.entity.d.ts
  project/dist/src/games/entities/socketIdMap.entity.js
  project/dist/src/games/entities/socketIdMap.entity.js.map
  project/dist/src/games/games.gateway.d.ts
  project/dist/src/games/games.gateway.js
  project/dist/src/games/games.gateway.js.map
  project/dist/src/games/players.service.d.ts
  project/dist/src/games/players.service.js
  project/dist/src/games/players.service.js.map
  project/dist/src/games/util/event.user.info.constructor.d.ts
  project/dist/src/games/util/event.user.info.constructor.js
  project/dist/src/games/util/event.user.info.constructor.js.map
  project/dist/src/users/users.service.js
  project/dist/src/users/users.service.js.map
  project/dist/tsconfig.build.tsbuildinfo
  project/src/games/dto/socketId-map.request.dto.ts
  project/src/games/entities/socketIdMap.entity.ts
  project/src/games/games.gateway.ts
  project/src/games/players.service.ts
  project/src/games/util/event.user.info.constructor.ts
  project/src/users/users.service.ts
Labels: bug, :smile_cat: backend

#164 FEAT : 키워드 엑셀 파일 추가
  project/dist/tsconfig.build.tsbuildinfo
  project/src/keyword/keyword_ver.20230202_a.xlsx
Labels: enhancement, :smile_cat: backend

#169 FEAT: [게임 중] 발표자 탈주시 처리 #136
  project/dist/src/app.controller.d.ts
  project/dist/src/app.controller.js
  project/dist/src/app.controller.js.map
  project/dist/src/common/exceptionFilters/ws-exception.filter.js
  project/dist/src/common/exceptionFilters/ws-exception.filter.js.map
  project/dist/src/games/chat.service.d.ts
  project/dist/src/games/chat.service.js
  project/dist/src/games/chat.service.js.map
  project/dist/src/games/dto/turn-result.data.insert.dto.d.ts
  project/dist/src/games/dto/turn-result.data.insert.dto.js
  project/dist/src/games/dto/turn-result.data.insert.dto.js.map
  project/dist/src/games/entities/turnResult.entity.d.ts
  project/dist/src/games/entities/turnResult.entity.js
  project/dist/src/games/entities/turnResult.entity.js.map
  project/dist/src/games/games.gateway.d.ts
  project/dist/src/games/games.gateway.js
  project/dist/src/games/games.gateway.js.map
  project/dist/src/games/games.service.d.ts
  project/dist/src/games/games.service.js
  project/dist/src/games/games.service.js.map
  project/dist/src/games/players.service.d.ts
  project/dist/src/games/players.service.js
  project/dist/src/games/players.service.js.map
  project/dist/src/games/room.service.js
  project/dist/src/games/room.service.js.map
  project/dist/src/games/util/game-timer.map.d.ts
  project/dist/src/games/util/game-timer.map.js
  project/dist/src/games/util/game-timer.map.js.map
  project/dist/src/games/util/game.map.d.ts
  project/dist/src/games/util/game.map.js
  project/dist/src/games/util/game.map.js.map
  project/dist/src/games/util/score.map.d.ts
  project/dist/src/games/util/score.map.js
  project/dist/src/games/util/score.map.js.map
  project/dist/src/games/util/today.date.constructor.d.ts
  project/dist/src/games/util/today.date.constructor.js
  project/dist/src/games/util/today.date.constructor.js.map
  project/dist/src/games/util/turn.map.d.ts
  project/dist/src/games/util/turn.map.js
  project/dist/src/games/util/turn.map.js.map
  project/dist/src/users/users.controller.d.ts
  project/dist/src/users/users.service.d.ts
  project/dist/src/users/users.service.js
  project/dist/src/users/users.service.js.map
  project/dist/tsconfig.build.tsbuildinfo
  project/src/app.controller.ts
  project/src/common/exceptionFilters/ws-exception.filter.ts
  project/src/games/chat.service.ts
  project/src/games/dto/turn-result.data.insert.dto.ts
  project/src/games/entities/turnResult.entity.ts
  project/src/games/games.gateway.ts
  project/src/games/games.service.ts
  project/src/games/players.service.ts
  project/src/games/room.service.ts
  project/src/games/util/game-timer.map.ts
  project/src/games/util/game.map.ts
  project/src/games/util/score.map.ts
  project/src/games/util/today.date.constructor.ts
  project/src/games/util/turn.map.ts
  project/src/users/users.service.ts
Labels: bug, enhancement, :smile_cat: backend, refactoring

#173 FIX : 탈주자 처리시 update-room event 오류 나는 것 해결하기 #171
  .gitignore
  project/dist/src/app.controller.d.ts
  project/dist/src/app.controller.js
  project/dist/src/app.controller.js.map
  project/dist/src/app.module.js
  project/dist/src/app.module.js.map
  project/dist/src/games/chat.service.js
  project/dist/src/games/chat.service.js.map
  project/dist/src/games/games.gateway.d.ts
  project/dist/src/games/games.gateway.js
  project/dist/src/games/games.gateway.js.map
  project/dist/src/games/games.module.js
  project/dist/src/games/games.module.js.map
  project/dist/src/games/games.service.d.ts
  project/dist/src/games/games.service.js
  project/dist/src/games/games.service.js.map
  project/dist/src/games/room.service.js
  project/dist/src/games/room.service.js.map
  project/dist/src/keyword/entities/keyword.entities.d.ts
  project/dist/src/keyword/entities/keyword.entities.js
  project/dist/src/keyword/entities/keyword.entities.js.map
  project/dist/src/keyword/keyword.module.js
  project/dist/src/keyword/keyword.module.js.map
  project/dist/src/keyword/keyword.service.d.ts
  project/dist/src/keyword/keyword.service.js
  project/dist/src/keyword/keyword.service.js.map
  project/dist/src/logger/winston.util.js
  project/dist/src/logger/winston.util.js.map
  project/dist/src/users/auth/jwt.guard.js
  project/dist/src/users/auth/jwt.guard.js.map
  project/dist/src/users/auth/kakao.data.d.ts
  project/dist/src/users/auth/kakao.data.js
  project/dist/src/users/auth/kakao.data.js.map
  project/dist/src/users/auth/kakao.serializer.js
  project/dist/src/users/auth/kakao.serializer.js.map
  project/dist/src/users/auth/token.data.d.ts
  project/dist/src/users/auth/token.data.js
  project/dist/src/users/auth/token.data.js.map
  project/dist/src/users/users.module.js
  project/dist/src/users/users.module.js.map
  project/dist/tsconfig.build.tsbuildinfo
  project/src/app.controller.ts
  project/src/app.module.ts
  project/src/games/chat.service.ts
  project/src/games/games.gateway.ts
  project/src/games/games.module.ts
  project/src/games/games.service.ts
  project/src/games/room.service.ts
  project/src/keyword/entities/keyword.entities.ts
  project/src/keyword/keyword.module.ts
  project/src/keyword/keyword.service.ts
  project/src/keyword/keyword.util.ts
  project/src/logger/winston.util.ts
  project/src/users/auth/jwt.guard.ts
  project/src/users/auth/kakao.data.ts
  project/src/users/auth/kakao.serializer.ts
  project/src/users/auth/token.data.ts
  project/src/users/users.module.ts
Labels: bug, :smile_cat: backend

#175 FIX : JS에서 생성하는 Date 객체 시간 맞추기 #174
  project/dist/src/games/util/today.date.constructor.js
  project/dist/src/games/util/today.date.constructor.js.map
  project/dist/tsconfig.build.tsbuildinfo
  project/src/games/util/today.date.constructor.ts
Labels: bug, :smile_cat: backend, :bulb: remind

#179 FEAT : pm2 무중단 서버배포 설정
  project/dist/tsconfig.build.tsbuildinfo
  project/ecosystem.config.js
Labels: enhancement, :smile_cat: backend

#182 FIX : 첫 배포 후 나는 문제들 수정
  project/dataSource.ts
  project/dist/dataSource.js
  project/dist/dataSource.js.map
  project/dist/src/users/auth/kakao.strategy.js
  project/dist/src/users/auth/kakao.strategy.js.map
  project/dist/tsconfig.build.tsbuildinfo
  project/ecosystem.config.js
  project/package.json
  project/src/users/auth/kakao.strategy.ts
Labels: bug, :smile_cat: backend, release

#183 FIX : 배포 후 hotfix한 내용 dev와 동기화
  project/dataSource.ts
  project/dist/dataSource.js
  project/dist/dataSource.js.map
  project/dist/src/users/auth/kakao.strategy.js
  project/dist/src/users/auth/kakao.strategy.js.map
  project/dist/tsconfig.build.tsbuildinfo
  project/ecosystem.config.js
  project/package.json
  project/src/users/auth/kakao.strategy.ts
Labels: :smile_cat: backend

#190 RELEASE : v0.2.0
  project/dist/src/games/chat.service.js
  project/dist/src/games/chat.service.js.map
  project/dist/src/games/games.gateway.js
  project/dist/src/games/games.gateway.js.map
  project/dist/src/games/games.service.d.ts
  project/dist/src/games/games.service.js
  project/dist/src/games/games.service.js.map
  project/dist/src/logger/winston.util.js
  project/dist/src/logger/winston.util.js.map
  project/dist/tsconfig.build.tsbuildinfo
  project/src/games/chat.service.ts
  project/src/games/games.gateway.ts
  project/src/games/games.service.ts
  project/src/logger/winston.util.ts
Labels: :smile_cat: backend, release

#192 FIX: 스코어 반영 문제 #191
  project/dist/src/games/games.gateway.js
  project/dist/src/games/games.gateway.js.map
  project/dist/src/games/games.service.js
  project/dist/src/games/games.service.js.map
  project/dist/tsconfig.build.tsbuildinfo
  project/src/games/games.gateway.ts
  project/src/games/games.service.ts
Labels: bug, :smile_cat: backend, :bulb: remind

#195 FIX : 비밀방 비밀번호에 0을 포함한 숫자 4자리로 생성/입장하도록 수정 #194
  project/dist/src/games/dto/create-room.request.dto.d.ts
  project/dist/src/games/dto/create-room.request.dto.js
  project/dist/src/games/dto/create-room.request.dto.js.map
  project/dist/src/games/dto/enter-room.request.dto.d.ts
  project/dist/src/games/dto/enter-room.request.dto.js
  project/dist/src/games/dto/enter-room.request.dto.js.map
  project/dist/src/games/entities/room.entity.d.ts
  project/dist/src/games/entities/room.entity.js
  project/dist/src/games/entities/room.entity.js.map
  project/dist/src/games/games.gateway.d.ts
  project/dist/src/games/games.gateway.js.map
  project/dist/src/games/room.service.d.ts
  project/dist/src/games/room.service.js
  project/dist/src/games/room.service.js.map
  project/dist/tsconfig.build.tsbuildinfo
  project/src/games/dto/create-room.request.dto.ts
  project/src/games/dto/enter-room.request.dto.ts
  project/src/games/entities/room.entity.ts
  project/src/games/games.gateway.ts
  project/src/games/room.service.ts
Labels: bug, :smile_cat: backend, :fire: hotfix

#199 FIX : user entity kakaoUserId 컬럼 bigint로 타입 전환 #9
  project/dist/src/users/entities/user.entity.js
  project/dist/src/users/entities/user.entity.js.map
  project/dist/tsconfig.build.tsbuildinfo
  project/src/users/entities/user.entity.ts
Labels: bug, :smile_cat: backend

#202 FEAT : 키워드 힌트 및 용어 해설 링크 추가 #201
  project/dist/src/admin/cron.service.js
  project/dist/src/admin/cron.service.js.map
  project/dist/src/games/dto/turn-result.data.insert.dto.d.ts
  project/dist/src/games/dto/turn-result.data.insert.dto.js
  project/dist/src/games/dto/turn-result.data.insert.dto.js.map
  project/dist/src/games/dto/turn.data.insert.dto.d.ts
  project/dist/src/games/dto/turn.data.insert.dto.js
  project/dist/src/games/dto/turn.data.insert.dto.js.map
  project/dist/src/games/entities/turn.entity.d.ts
  project/dist/src/games/entities/turn.entity.js
  project/dist/src/games/entities/turn.entity.js.map
  project/dist/src/games/entities/turnResult.entity.d.ts
  project/dist/src/games/entities/turnResult.entity.js
  project/dist/src/games/entities/turnResult.entity.js.map
  project/dist/src/games/games.gateway.js
  project/dist/src/games/games.gateway.js.map
  project/dist/src/games/games.service.d.ts
  project/dist/src/games/games.service.js
  project/dist/src/games/games.service.js.map
  project/dist/src/keyword/entities/keyword.entities.d.ts
  project/dist/src/keyword/entities/keyword.entities.js
  project/dist/src/keyword/entities/keyword.entities.js.map
  project/dist/src/keyword/keyword.service.js
  project/dist/src/keyword/keyword.service.js.map
  project/dist/src/users/users.controller.js
  project/dist/src/users/users.controller.js.map
  project/dist/src/users/users.service.js
  project/dist/src/users/users.service.js.map
  project/dist/tsconfig.build.tsbuildinfo
  project/src/admin/cron.service.ts
  project/src/games/dto/turn-result.data.insert.dto.ts
  project/src/games/dto/turn.data.insert.dto.ts
  project/src/games/entities/turn.entity.ts
  project/src/games/entities/turnResult.entity.ts
  project/src/games/games.gateway.ts
  project/src/games/games.service.ts
  project/src/keyword/entities/keyword.entities.ts
  project/src/keyword/keyword.service.ts
  project/src/users/users.controller.ts
  project/src/users/users.service.ts
Labels: enhancement, :smile_cat: backend

#200 FIX : 깃허브 액션파일 변경
  .github/workflows/main.yml
Labels: :smile_cat: backend, :fire: hotfix

#205 FIX : 잘못 올라간 커밋 내용 삭제 #204
  project/dist/src/admin/cron.service.js
  project/dist/src/admin/cron.service.js.map
  project/dist/src/games/games.gateway.js
  project/dist/src/games/games.gateway.js.map
  project/dist/src/games/games.service.d.ts
  project/dist/src/games/games.service.js
  project/dist/src/games/games.service.js.map
  project/dist/src/users/users.controller.js
  project/dist/src/users/users.controller.js.map
  project/dist/tsconfig.build.tsbuildinfo
  project/src/admin/cron.service.ts
  project/src/games/games.gateway.ts
  project/src/games/games.service.ts
  project/src/users/users.controller.ts
Labels: bug, :smile_cat: backend, :fire: hotfix

#206 FIX : 잘못 올라간 커밋 내용 삭제 #204
  README.md
  project/dist/src/admin/cron.service.js
  project/dist/src/admin/cron.service.js.map
  project/dist/src/games/games.gateway.js
  project/dist/src/games/games.gateway.js.map
  project/dist/src/games/games.service.d.ts
  project/dist/src/games/games.service.js
  project/dist/src/games/games.service.js.map
  project/dist/src/users/users.controller.js
  project/dist/src/users/users.controller.js.map
  project/dist/tsconfig.build.tsbuildinfo
  project/src/admin/cron.service.ts
  project/src/games/games.gateway.ts
  project/src/games/games.service.ts
  project/src/users/users.controller.ts
Labels: bug, :smile_cat: backend, :fire: hotfix
