Repository gachimind/backend, pull requests merged in 2023-01, with the labels that each got.

#3 CHORE: 프로젝트 초기 세팅 #1
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/fix-report.md
  .github/pull_request_template.md
  .gitignore
  README.md
  project/.eslintrc.js
  project/.gitignore
  project/.prettierrc
  project/README.md
  project/nest-cli.json
  project/package-lock.json
  project/package.json
  project/src/app.module.ts
  project/src/common/interceptors/undefinedToNull.interceptor.ts
  project/src/games/chat.service.spec.ts
  project/src/games/chat.service.ts
  project/src/games/dto/create-room.dto.ts
  project/src/games/dto/enter-room.dto.ts
  project/src/games/dto/room.info.dto.ts
  project/src/games/games.gateway.spec.ts
  project/src/games/games.gateway.ts
  project/src/games/games.module.ts
  project/src/games/room.service.spec.ts
  project/src/games/room.service.ts
  project/src/http-exception.filter.ts
  project/src/main.ts
  project/src/middlewares/logger.middleware.ts
  project/src/users/dto/create-user.dto.ts
  project/src/users/dto/login-user.dto.ts
  project/src/users/dto/update-user.dto.ts
  project/src/users/entities/user.entity.ts
  project/src/users/users.controller.spec.ts
  project/src/users/users.controller.ts
  project/src/users/users.module.ts
  project/src/users/users.service.spec.ts
  project/src/users/users.service.ts
  project/test/app.e2e-spec.ts
  project/test/jest-e2e.json
  project/tsconfig.build.json
  project/tsconfig.json
  project/webpack-hmr.config.js
Labels: documentation, good first issue, backend

#30 FIX : HTTP exception filter 수정 #29
  project/src/common/exceptionFilters/http-exception.filter.ts
  project/src/main.ts
  project/src/users/users.controller.ts
Labels: bug, :smile_cat: backend

#34 FEAT: 2차 스프린트 socket API 개발 #33
  project/package-lock.json
  project/package.json
  project/src/common/exceptionFilters/ws-exception.filter.ts
  project/src/games/chat.service.spec.ts
  project/src/games/dto/create-room.dto.ts
  project/src/games/dto/room.info.dto.ts
  project/src/games/games.gateway.spec.ts
  project/src/games/games.gateway.ts
  project/src/games/room.service.spec.ts
  project/src/main.ts
  project/src/middlewares/logger.middleware.ts
  project/src/users/users.controller.spec.ts
  project/src/users/users.service.spec.ts
  project/test/app.e2e-spec.ts
Labels: enhancement, :smile_cat: backend

#38 FEAT : 카카오 로그인 Oauth 구현 및 회원정보조회 API 정리 완료
  project/.gitignore
  project/package-lock.json
  project/package.json
  project/src/types/express/index.d.ts
  project/src/users/auth/auth.service.ts
  project/src/users/auth/kakao.guards.ts
  project/src/users/auth/kakao.serializer.ts
  project/src/users/auth/kakao.strategy.ts
  project/src/users/users.controller.ts
  project/src/users/users.module.ts
  project/src/users/users.service.ts
  project/tsconfig.json
Labels: enhancement, :smile_cat: backend

#42 FEAT: Github Actions으로 배포 자동화하기 #35
  .github/workflows/main.yml
Labels: enhancement, :smile_cat: backend

#48 FEAT : [socket] update-room event emit 데이터 추가#46
  project/src/games/games.gateway.ts
Labels: enhancement, :smile_cat: backend

#69 FEAT : [게임대기] 게임 READY API #14
  project/dist/src/games/games.gateway.d.ts
  project/dist/src/games/games.gateway.js
  project/dist/src/games/games.gateway.js.map
  project/dist/src/games/players.service.d.ts
  project/dist/src/games/players.service.js
  project/dist/src/games/players.service.js.map
  project/dist/src/games/room.service.d.ts
  project/dist/src/games/room.service.js
  project/dist/src/games/room.service.js.map
  project/dist/src/games/util/participants-list.mapper.d.ts
  project/dist/src/games/util/participants-list.mapper.js
  project/dist/src/games/util/participants-list.mapper.js.map
  project/dist/src/games/util/update-room.info.to.room.constructor.d.ts
  project/dist/src/games/util/update-room.info.to.room.constructor.js
  project/dist/src/games/util/update-room.info.to.room.constructor.js.map
  project/dist/tsconfig.build.tsbuildinfo
  project/src/games/games.gateway.ts
  project/src/games/players.service.ts
  project/src/games/room.service.ts
  project/src/games/util/participants-list.mapper.ts
  project/src/games/util/update-room.info.to.room.constructor.ts
Labels: enhancement, :smile_cat: backend

#78 FEAT : isGameReadyToStart 업데이트 이벤트 추가하기#74
  project/dist/src/games/dto/roomInfoToMain.dto.d.ts
  project/dist/src/games/dto/roomInfoToMain.dto.js
  project/dist/src/games/dto/roomInfoToMain.dto.js.map
  project/dist/src/games/dto/update-room.dto.d.ts
  project/dist/src/games/dto/update-room.dto.js
  project/dist/src/games/dto/update-room.dto.js.map
  project/dist/src/games/games.gateway.d.ts
  project/dist/src/games/games.gateway.js
  project/dist/src/games/games.gateway.js.map
  project/dist/src/games/room.service.js
  project/dist/src/games/room.service.js.map
  project/dist/src/games/util/update-room.info.constructor.d.ts
  project/dist/src/games/util/update-room.info.constructor.js
  project/dist/src/games/util/update-room.info.constructor.js.map
  project/dist/src/games/util/update-room.info.to.room.constructor.js.map
  project/dist/tsconfig.build.tsbuildinfo
  project/src/games/dto/roomInfoToMain.dto.ts
  project/src/games/dto/update-room.dto.ts
  project/src/games/games.gateway.ts
  project/src/games/room.service.ts
  project/src/games/util/update-room.info.constructor.ts
Labels: enhancement, :smile_cat: backend, refactoring

#86 FIX : socketAuthentication 에러 메세지 및 이중 로그인 처리 로직 수정 #83
  project/src/games/games.gateway.ts
  project/src/games/players.service.ts
Labels: bug, :smile_cat: backend

#92 FIX : 프런트에 쿠키 전달을 위해 배포 버전에 cors 옵션 수정#91
  project/dist/src/games/dto/create-room.request.dto.d.ts
  project/dist/src/games/dto/create-room.request.dto.js
  project/dist/src/games/dto/create-room.request.dto.js.map
  project/dist/src/games/entities/room.entity.d.ts
  project/dist/src/games/entities/room.entity.js
  project/dist/src/games/entities/room.entity.js.map
  project/dist/src/games/games.gateway.d.ts
  project/dist/src/games/games.gateway.js
  project/dist/src/games/games.gateway.js.map
  project/dist/src/games/players.service.js
  project/dist/src/games/players.service.js.map
  project/dist/src/games/room.service.js
  project/dist/src/games/room.service.js.map
  project/dist/src/games/util/update-room.info.constructor.js
  project/dist/src/games/util/update-room.info.constructor.js.map
  project/dist/src/main.js
  project/dist/src/main.js.map
  project/dist/src/users/auth/jwt.guard.js
  project/dist/src/users/auth/jwt.guard.js.map
  project/dist/src/users/auth/kakao.serializer.js
  project/dist/src/users/auth/kakao.serializer.js.map
  project/dist/src/users/auth/kakao.strategy.js
  project/dist/src/users/auth/kakao.strategy.js.map
  project/dist/src/users/dto/create-user.dto.d.ts
  project/dist/src/users/dto/create-user.dto.js
  project/dist/src/users/dto/create-user.dto.js.map
  project/dist/src/users/entities/token-map.entity.js
  project/dist/src/users/entities/token-map.entity.js.map
  project/dist/src/users/entities/user.entity.d.ts
  project/dist/src/users/entities/user.entity.js
  project/dist/src/users/entities/user.entity.js.map
  project/dist/src/users/users.controller.d.ts
  project/dist/src/users/users.controller.js
  project/dist/src/users/users.controller.js.map
  project/dist/src/users/users.module.js
  project/dist/src/users/users.module.js.map
  project/dist/src/users/users.service.d.ts
  project/dist/src/users/users.service.js
  project/dist/src/users/users.service.js.map
  project/dist/tsconfig.build.tsbuildinfo
  project/src/games/dto/create-room.request.dto.ts
  project/src/games/entities/room.entity.ts
  project/src/games/games.gateway.ts
  project/src/games/players.service.ts
  project/src/games/room.service.ts
  project/src/games/util/update-room.info.constructor.ts
  project/src/main.ts
  project/src/users/auth/jwt.guard.ts
  project/src/users/auth/kakao.serializer.ts
  project/src/users/auth/kakao.strategy.ts
  project/src/users/dto/create-user.dto.ts
  project/src/users/entities/token-map.entity.ts
  project/src/users/entities/user.entity.ts
  project/src/users/users.controller.ts
  project/src/users/users.module.ts
  project/src/users/users.service.ts
Labels: bug, :smile_cat: backend, release

#105 FIX : valid-room-password에서 유저 검증 로직 추가 #103
  project/dist/src/games/games.gateway.js
  project/dist/src/games/games.gateway.js.map
  project/dist/tsconfig.build.tsbuildinfo
  project/src/games/games.gateway.ts
Labels: bug, :smile_cat: backend

#117 FIX : start 이벤트 내에서 while 문 오류 #112
  project/dist/src/common/exceptionFilters/ws-exception.filter.d.ts
  project/dist/src/common/exceptionFilters/ws-exception.filter.js
  project/dist/src/common/exceptionFilters/ws-exception.filter.js.map
  project/dist/src/games/games.gateway.d.ts
  project/dist/src/games/games.gateway.js
  project/dist/src/games/games.gateway.js.map
  project/dist/src/games/games.service.js.map
  project/dist/tsconfig.build.tsbuildinfo
  project/src/common/exceptionFilters/ws-exception.filter.ts
  project/src/games/games.gateway.ts
  project/src/games/games.service.ts
Labels: bug, :smile_cat: backend

#125 CHORE : 최신 dev브랜치와 머지 및 추가 패키지 설치 & 클라이언트로 내려가는 에러 메세지 수정
  project/dist/dataSource.js
  project/dist/dataSource.js.map
  project/dist/src/app.module.js
  project/dist/src/app.module.js.map
  project/dist/src/common/exceptionFilters/ws-exception.filter.d.ts
  project/dist/src/common/exceptionFilters/ws-exception.filter.js
  project/dist/src/common/exceptionFilters/ws-exception.filter.js.map
  project/dist/src/keyword/entities/keyword.entities.d.ts
  project/dist/src/keyword/entities/keyword.entities.js
  project/dist/src/keyword/entities/keyword.entities.js.map
  project/dist/src/keyword/keyword.controller.d.ts
  project/dist/src/keyword/keyword.controller.js
  project/dist/src/keyword/keyword.controller.js.map
  project/dist/src/keyword/keyword.module.d.ts
  project/dist/src/keyword/keyword.module.js
  project/dist/src/keyword/keyword.module.js.map
  project/dist/src/keyword/keyword.service.d.ts
  project/dist/src/keyword/keyword.service.js
  project/dist/src/keyword/keyword.service.js.map
  project/dist/tsconfig.build.tsbuildinfo
  project/package-lock.json
  project/package.json
  project/src/common/exceptionFilters/ws-exception.filter.ts
Labels: bug, :smile_cat: backend

#129 FIX : gameResult 엔티티 생성시 todayResult id 조회하여 추가 및 채팅 로직 수정 #127
  project/dataSource.ts
  project/dist/dataSource.js
  project/dist/dataSource.js.map
  project/dist/src/app.module.js
  project/dist/src/app.module.js.map
  project/dist/src/games/entities/gameResult.entity.js
  project/dist/src/games/entities/gameResult.entity.js.map
  project/dist/src/games/entities/todayResult.entity.d.ts
  project/dist/src/games/entities/todayResult.entity.js
  project/dist/src/games/entities/todayResult.entity.js.map
  project/dist/src/games/games.gateway.js
  project/dist/src/games/games.gateway.js.map
  project/dist/src/games/games.service.d.ts
  project/dist/src/games/games.service.js
  project/dist/src/games/games.service.js.map
  project/dist/src/games/players.service.d.ts
  project/dist/src/games/players.service.js
  project/dist/src/games/players.service.js.map
  project/dist/src/games/util/today.date.constructor.d.ts
  project/dist/src/games/util/today.date.constructor.js
  project/dist/src/games/util/today.date.constructor.js.map
  project/dist/tsconfig.build.tsbuildinfo
  project/src/app.module.ts
  project/src/games/entities/gameResult.entity.ts
  project/src/games/entities/todayResult.entity.ts
  project/src/games/games.gateway.ts
  project/src/games/games.service.ts
  project/src/games/players.service.ts
  project/src/games/util/today.date.constructor.ts
Labels: bug, enhancement, :smile_cat: backend

#145 FEAT : 로그아웃 API
  project/dist/src/users/users.controller.d.ts
  project/dist/src/users/users.controller.js
  project/dist/src/users/users.controller.js.map
  project/dist/src/users/users.service.d.ts
  project/dist/src/users/users.service.js
  project/dist/src/users/users.service.js.map
  project/dist/tsconfig.build.tsbuildinfo
  project/src/users/users.controller.ts
  project/src/users/users.service.ts
Labels: enhancement, :smile_cat: backend

#147 FIX : 회원가입시 이메일 제공 선택 안할때 500 에러, users/me api score 정보 조회 오류, 기본 고양이 값 변경 #128
  project/dist/src/users/auth/kakao.strategy.js
  project/dist/src/users/auth/kakao.strategy.js.map
  project/dist/src/users/users.controller.d.ts
  project/dist/src/users/users.service.d.ts
  project/dist/src/users/users.service.js
  project/dist/src/users/users.service.js.map
  project/dist/tsconfig.build.tsbuildinfo
  project/src/users/auth/kakao.strategy.ts
  project/src/users/users.service.ts
Labels: bug, enhancement, :smile_cat: backend, refactoring

#149 FEAT : [회원] 회원정보조회시 isFirstLogin 추가 & 가입시 닉네임 중복이면 숫자 붙이기 #146
  project/dist/src/app.controller.d.ts
  project/dist/src/app.controller.js
  project/dist/src/app.controller.js.map
  project/dist/src/users/auth/kakao.serializer.js
  project/dist/src/users/auth/kakao.serializer.js.map
  project/dist/src/users/dto/create-user.dto.d.ts
  project/dist/src/users/dto/create-user.dto.js
  project/dist/src/users/dto/create-user.dto.js.map
  project/dist/src/users/entities/user.entity.d.ts
  project/dist/src/users/entities/user.entity.js
  project/dist/src/users/entities/user.entity.js.map
  project/dist/src/users/users.controller.js
  project/dist/src/users/users.controller.js.map
  project/dist/src/users/users.service.d.ts
  project/dist/src/users/users.service.js
  project/dist/src/users/users.service.js.map
  project/dist/tsconfig.build.tsbuildinfo
  project/src/app.controller.ts
  project/src/users/auth/kakao.serializer.ts
  project/src/users/dto/create-user.dto.ts
  project/src/users/entities/user.entity.ts
  project/src/users/users.controller.ts
  project/src/users/users.service.ts
Labels: enhancement, :smile_cat: backend
